name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'preview'
        type: choice
        options:
        - preview
        - production

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
        
    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
      
    - name: Setup environment variables
      working-directory: ./frontend
      run: |
        echo "EXPO_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env.production
        
    - name: Build APK for Preview
      if: github.event.inputs.build_type == 'preview' || github.event.inputs.build_type == ''
      working-directory: ./frontend
      run: eas build --platform android --profile preview --non-interactive --no-wait
      
    - name: Build APK for Production
      if: github.event.inputs.build_type == 'production'
      working-directory: ./frontend
      run: eas build --platform android --profile production --non-interactive --no-wait
      
    - name: Get build URL
      working-directory: ./frontend
      run: |
        BUILD_URL=$(eas build:list --json --limit=1 | jq -r '.[0].artifacts.buildUrl // empty')
        echo "Build URL: $BUILD_URL"
        echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV
        
    - name: Comment build result
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '📱 Android build started! Check your Expo dashboard for progress and download link.'
          })